apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: burguerspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: "50%"
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: lkhouri/api:v1
        ports:
        - containerPort: 80
