apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: burguerspace
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 80
      nodePort: 30479
  type: NodePort
