version: '3.8'
services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root@123
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
      - ./data/configdb:/data/configdb
      - ./init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro 
  api:
    image: lkhouri/api:v1
    build: ./Api
    ports:
      - "8080:80"
    depends_on:
      - mongo