version: '3.8'

networks:
  app-network:
    driver: bridge

volumes:
  mongodata:

services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2024!
    expose:
      - 27017
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongodata:/data/db

  api:
    image: lkhouri/api:v1
    build: ./Api
    ports:
      - "5000:80"
    networks:
      - app-network
    depends_on:
      - mongo
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: always
    expose:
      - 15672
    ports:
      - "5672:5672"  # Porta para AMQP
      - "15672:15672"  # Porta para o painel de controle do RabbitMQ (opcional, para acesso ao RabbitMQ Management)
    networks:
      - app-network
    environment:
      RABBITMQ_DEFAULT_USER: "guest"  
      RABBITMQ_DEFAULT_PASS: "guest"  
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
