version: '3.8'

volumes:
  postgres_data:

services:
  api:
    image: lkhouri/cheeseapi:v1
    build: ./Api
    ports:
      - "5000:80"
    depends_on:
      - pgdb
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: always
    expose:
      - 15672
    ports:
      - "5672:5672"  # Porta para AMQP
      - "15672:15672"  # Porta para o painel de controle do RabbitMQ (opcional, para acesso ao RabbitMQ Management)
    environment:
      RABBITMQ_DEFAULT_USER: "guest"  
      RABBITMQ_DEFAULT_PASS: "guest"  
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  pgdb:
    image: postgres:latest
    environment:
      POSTGRES_DB: db-burger
      POSTGRES_USER: passUser
      POSTGRES_PASSWORD: pass@123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U passUser -d db-burger"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "leonardock9@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "pass@123"
    ports:
      - "5050:80"
    depends_on:
      - pgdb
    volumes:
    - "./servers.json:/pgadmin4/servers.json"
