apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: burguerspace
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "dbBurger"
        - name: POSTGRES_USER
          value: "pass"
        - name: POSTGRES_PASSWORD
          value: "pass45455627"
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
