name: .NET 8 Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME}}
    steps:
    - uses: actions/checkout@v3

    - name: Setup.NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore FiapTechChallenge/FiapTechChallenge.sln

    - name: Build
      run: dotnet build FiapTechChallenge/FiapTechChallenge.sln --no-restore

    - name: Run tests
      run: dotnet test FiapTechChallenge/Domain.Tests/Domain.Tests.csproj --no-build

  build-and-push-docker-image:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: needs.build-and-test.result == 'success'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build the Docker image
        working-directory: FiapTechChallenge
        run: |
          docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/cheeseapi:v1 .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
     
      - name: Push the image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/cheeseapi:v1

  deploy-to-eks:
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image
    if: needs.build-and-push-docker-image.result == 'success'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Update kubeconfig with EKS cluster credentials
        run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region us-east-1

      - name: Deploy to EKS
        run: | 
          kubectl apply -f api-deployment.yaml
          kubectl apply -f api-hpa.yaml
          kubectl apply -f api-service.yaml
          kubectl apply -f postgres-pvc.yaml
          kubectl apply -f postgres-service.yaml
          kubectl apply -f rabbitmq-deployment.yaml
          kubectl apply -f rabbitmq-service.yaml