name: .NET 8 Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup.NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore FiapTechChallenge/FiapTechChallenge.sln

    - name: Build
      run: dotnet build FiapTechChallenge/FiapTechChallenge.sln --no-restore

    - name: Run tests
      run: dotnet test FiapTechChallenge/Domain.Tests/Domain.Tests.csproj --no-build

  build-and-push-docker-image:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: needs.build-and-test.result == 'success'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print current directory
        run: ls -l

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -f ./Api/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/cheeseapi:v1 .
          docker push ${{ secrets.DOCKER_USERNAME }}/cheeseapi:v1
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/cheeseapi:v1
        working-directory: ./Api